# Generated by Django 4.1.5 on 2023-05-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics_service', '0002_remove_iphone_number_alter_iphone_memory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='iphone',
            name='date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web_analytics_service.date'),
            preserve_default=False,
        ),
    ]
