# Generated by Django 4.1.5 on 2023-05-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics_service', '0003_date_iphone_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='DateAdd',
        ),
    ]
