# Generated by Django 4.1.5 on 2023-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics_service', '0004_rename_date_dateadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateadd',
            name='date_value',
            field=models.DateTimeField(),
        ),
    ]
