# Generated by Django 4.1.5 on 2023-05-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics_service', '0005_alter_dateadd_date_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='DateAdd',
        ),
    ]
