# Generated by Django 4.1.5 on 2023-05-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics_service', '0006_alter_iphone_date_delete_dateadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='link',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
