# Generated by Django 4.1.5 on 2023-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics_service', '0008_alter_iphone_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='date',
            field=models.DateField(verbose_name='%Y/%m/%d'),
        ),
    ]
