# Generated by Django 4.1.5 on 2023-05-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics_service', '0009_alter_iphone_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='iphone',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_analytics_service.dateadd'),
        ),
    ]
